--Part – A:
--1. Update SPI of all students from 7.00 to 8.00.

--2. Change city of HETVI from RAJKOT to AHMEDABAD.
--3. Update SPI of DEEP to 9.20 and city to VADODARA.
--4. Update SPI of DHARMIK to 8.50.
--5. Update branch name from COMPUTER to IT.
--6. Update branch of RAJ to AUTOMOBILE.
--7. Update SPI to 7.50 where STDID is between 103 and 107.
--8. Update city of PARAG to MUMBAI.
--9. Update SPI of RIYA to 6.00.
--10. Update SPI of SMAIR to 7.20 and branch to ELECTRICAL.
--Part – B:
--11. Give 10% increment in SPI.
--12. Increase SPI by 20% for all students.
--13. Increase SPI by 0.50 in all records.
--14. Update branch to 'EC' and SPI to 8.00 and city to Surat where SNAME is KRUNAL.
--15. Update city to 'RAJKOT' and SPI to 7.00 where branch is CIVIL and stdid is less than 105.
--Part – C:
--16. Update SPI of student with stdid 110 to NULL.
--17. Update branch of VISHAL to NULL.
--18. Display names of students whose SPI is NULL.
--19. Display students who have branch assigned.
--20. Update student with stdid 108 to name DARSHAN, branch COMPUTER, and SPI 8.50.
--21. Update city to SURAT where SPI is less than 7.00.
--22. Update city to NULL and branch to MECHANICAL where stdid is 109.